development:
  adapter: postgresql
  encoding: unicode
  database: roo_app_development
  pool: 5
  username: ericmooney
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: roo_app_test
  pool: 5
  username: ericmooney
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: roo_app_production
  pool: 5
  username: ericmooney
  password:
  host: localhost
